- Makefile.PL
- lib/OPCUA/Open62541.pm
This allows building the XS wrapper on the current Ubuntu 18.04.4 LTS release.
> Allow build for perl 5.26.1

- Open62541.xs
In case Perl is built with PERL_IMPLICIT_CONTEXT, extensions that call
functions in the Perl API will need to pass the initial context argument
somehow. OpenBSD does not compile Perl this way, but the default package
on Ubuntu does.
This change fixes the calls introduced in ec4bd83 for Perl with
IMPLICIT_CONTEXT according to man(1) perlguts in 'the most efficient
way' by passing the context as an extra argument.
> Fix calls to Perl API when Perl is compiled with IMPLICIT_CONTEXT

- Open62541.xs
* During unpack innerDiagnostic has to be initialized with new.
* During pack the key for innerDiagnostic in the perl hash should only
be set if the pointer to innerDiagnostic is not NULL.
> Fix recursive pack/unpack of UA_DiagnosticInfo

- lib/OPCUA/Open62541.pm
- lib/OPCUA/Open62541/Test/Client.pm
- lib/OPCUA/Open62541/Test/Logger.pm
- lib/OPCUA/Open62541/Test/Server.pm
- t/client-connect-async.t
- t/client-connect.t
- t/perlcriticrc
- t/test-client.t
- t/test-server.t
To avoid a race, the client must be started after the server has
bound the socket.  Redirect the server output to a log file and
grep for TCP listening.  Wait until the server is up or abort after
a timeout.
> Grep for server startup.

- Open62541.xs
- lib/OPCUA/Open62541/Test/Logger.pm
- lib/OPCUA/Open62541/Test/Server.pm
- t/logger-server.t
- t/logger.t
- typemap
Implement pack functions for UA_LogLevel and UA_LogCategory which
convert the values to number and string simultanously.  Test
the converted names.  Test logger writes names into log file
and all log messages to test output.
> Print log level and category as string.

- Open62541.xs
- lib/OPCUA/Open62541/Test/Client.pm
- lib/OPCUA/Open62541/Test/Logger.pm
- lib/OPCUA/Open62541/Test/Server.pm
- t/client-connect-async.t
- t/client-connect.t
- t/logger-client.t
- t/logger-server.t
New function getLogger() returns logger from client config.  The
test client creates a client.log file.  Test the client logger.
> Allow to replace the client logger.

- Open62541.xs
When reading data from client, we must pass a scalar reference to
retrieve the output value.  Instead of silently ignoring an invalid
type, better croak to find the bug.
> Croak if wrong output variable type.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/server-config-default.t
UA_ServerConfig_clean() is used for cleanup in the C layer.  It is
called automatically from server config delete.  It does not make
sense to expose it to the Perl layer.
> Server config clean() is not needed from Perl.

- lib/OPCUA/Open62541/Test/Client.pm
- t/client-browse-async.t
Call sendAsyncBrowseRequest() multiple times.  Check that request
id is unique.  Check that all request id are uses in callback.
> Test multiple browse request id.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- lib/OPCUA/Open62541/Test/Client.pm
- t/client-disconnect-async.t
Perl XS function UA_Client_disconnect_async takes optional scalar
reference to requestId.  Document $client->disconnect_async() in
pod.  Extend test client iterate to allow iteration until disconnect.
To be more flexible, a code ref to end iteration can be passed.
Add client-disconnect-async test.
> Implement client disconnect_async().

- Open62541.xs
- t/variant-array.t
- t/variant-scalar.t
String memory belongs to the SV.  When it is tranferred into a
variant, it has to be copied.  Use the copy functions to set the
value.
> Fix double free in set variant.

- lib/OPCUA/Open62541/Test/Server.pm
- t/server-iterate-singlestep.t
To make it easier to test error handling, this change introduces the
singlestep argument to Open62541::Test::Server. This allows a created
server to step the iterates one by one by calling step().
> Test::Server singlestep to enhance error handling tests

- Open62541.xs
- t/logger-client.t
- t/logger-server.t
- t/logger.t
Extend the lifetime of the logger, it should log until the client
or server is destroyed.  For that the OPCUA_Open62541_Logger with
the Perl SVs is pointed to by the client or server config's logger
context.  The OPCUA_Open62541_Logger reference counts the client
or server config storage.  So the Perl logger keeps the Perl client
or server alive, the client or server destroy function is the last
one to be called.  If the Perl reference of the OPCUA_Open62541_Logger
is destroyed, the object is not freed.  This is is done later from
the client or server destroy function.
> Free logger context from client and server destroy.

- lib/OPCUA/Open62541.pm
- t/client-connect-async.t
* In connect_async() open62541 starts an internal timer for every 100ms
to do the polling. This timed callback also creates the socket if it
does not exist yet.
* If the first run_iterate() is called before the callback will be
executed by open62541, the library will try to send the HEL message
with a non existent socket, which will result in an ENOTSOCK error.
> Fix async connect test

- Open62541.xs
- t/logger-client-multi.t
- t/logger-server-multi.t
Config getLogger() generates a OPCUA_Open62541_Logger object,
registers it in the client or server as logger context, and returns
a Perl reference to it.  If it was called a second time, the new
context replaced the old one, but was still referenced by its Perl
reference.  As a consequence, a following setCallback() used the
wrong context.  To avoid the Problem, getLogger() tries to use an
existing OPCUA_Open62541_Logger and returns it.  As we have distinct
Perl and C references, use an additional level of reference counting.
> Do not generate more than one logger object.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- lib/OPCUA/Open62541/Test/Logger.pm
- t/logger-leak.t
- t/logger.t
Creating a stand alone logger is not necessary.  It makes the code
more complicated and it may encourage users to use the wrong API.
Always get a logger from client or server config.
> Delete Logger->new() from API.

- MANIFEST
- lib/OPCUA/Open62541/Test/Server.pm
- t/test-server-runtimeaction.t
* The test server can start with a set of predefined actions, that can
be triggered when the child receives SIGUSR2.
> Implement test server runtime actions

- lib/OPCUA/Open62541/Test/Server.pm
- t/test-server-runtimeaction.t
- t/test-server-singlestep.t
Test server uses sigpending() and sigsuspend() to run next action.
The methods step() and next_action() in the test server parent wait
until the server sends an acknowledge signal.
> Remove signal race from test server.

- .github/workflows/main.yml
Use the github continuous integration framework to build the module and
run tests on push and pull requests. This first version uses one task to
install the requirements, build the software and test it. This could be
split up into different stages which pass the artifacts in the future,
if necessary.
> Enable github action

- Open62541-packed.xsh
- Open62541.xs
Main leak was that the generated pack input functions called calloc() without free() to convert arrays.  Use UA_Array for that and also allocate the strings.  Then all nested memory is allocated and can be freed with clear() or delete().  Unfortunately this has to be done manually in the cleanup section.
> Fix several memory leaks.

- .github/workflows/main.yml
- .gitignore
- MANIFEST.SKIP
- Makefile.PL
- t/unicode.t
Create unicode strings and utf-8 octets and pass them as strings
or byte strings to the test server.  Retrieve them with browse and
read request and check that they were not modified.  Write the
values to an UTF-8 text file and check that syswrite dies when
expected.  Convert the OPC UA hashes to YAML and test that it needs
the required encoding.
> Test unicode conversion of UPC UA string and byte string.

- lib/OPCUA/Open62541/Test/Server.pm
The test server setup_complex_objects() method printed a warning
"AddNodes: No datatype given; Copy the datatype attribute from the
TypeDefinition".  Adding a VariableAttributes_dataType fixes this.
> Avoid warning in test server.

- Open62541.xs
- t/server-variable.t
- t/typemap.t
- typemap
Move more of the parameter checks and memory management into the
typemap definitions.  The T_PTROBJ_PACKED typemap handles this.
The paramter name specifies whether it is a regular input, output
or optional output parameter.  The UA object for the input and
output parameter is generated on the fly and stored in a mortal SV.
The input parameter are unpacked automatically.  The mortal UA
object is available while the XS function is running.  After that
it is deleted by the DESTROY destructor.  The parameter checks and
explicit clear function in the funtions are no longer necessary.
Convert all UA_Node and UA_Variant parameter for now.
> Create mortal UA object in parameter typemap.

- Open62541-client-read.xsh
- Open62541.xs
- script/client-read.pl
- t/server-client-variable.t
DataTypeAttribute is special as it has to convert a node to a number.
This has to be implemented manually.  Implement the same output
conversion logic as in UA_Client_readDataTypeAttribute() into
clientAsyncReadDataTypeCallback().  The outDataType reference check
in UA_Client_readDataTypeAttribute() has moved to the typemap.
Implement UA_Client_readDataTypeAttribute_async() like the generated
one, but call clientAsyncReadDataTypeCallback.
> Implement client readDataTypeAttribute_async().

- Open62541.xs
- t/server-references.t
* NULL strings are already converted to undef in pack. Now the reverse
is happening in unpack.
* Extended a reference test where the library checks for NULL strings.
> UA_String unpack NULL string

- typemap
Use the recommended SvTYPE(SvRV(SV*)) < SVt_PVAV to detect scalar
references.  Put an additional sv_isobject() check to be stricter
and avoid a crash in the test.
> SVt_PVNV is not the correct way to detect scalars.

- Makefile.PL
- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/server-context.t
To provide a context for the global node livecycle callbacks,
implement server setAdminSessionContext() method.  As this is a new
API function, generate it only if it exists in the open62541 library.
> Set admin session context.

- Open62541.xs
- t/variant-array.t
- t/variant-scalar.t
Instead of printing a warnings that nobody reads, croak if there
is an interger or float overflow in the unpack functions.  Add some
tests for float and double variants.
> Integer and float overflow croak in unpack.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/server-node-lifecycle.t
- typemap
Set hash with global node livecycle callbacks.  Only the constructor
callback has been implemented.
> Implement global node livecycle callbacks.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/server-node-lifecycle.t
- t/variant-guid.t
- typemap
The formated Guid string as in Part 6, 5.1.3. seems to be the
easiest way to handle the Guid in Perl programs.  It can be printed
like all other node types.  The binary data we used before was
hard to work with.
> Pack and unpack Guid to formated Perl string.

- .github/workflows/main.yml
- Makefile.PL
- Open62541.xs
- t/client-connect-async.t
- t/client-disconnect-async.t
- t/client-leak.t
- t/test-server-singlestep.t
github CI uses open62541 library version 1.1 now.  Add some #ifdef to make p5-opcua-open62541 compile with the new library.  Update to Ubuntu 20.4.  Tests still fail, logger-client.t causes a segmentation fault.
> CI open62541 1.1

- Open62541.xs
- t/client-browse-async.t
Perl callbacks should be copied from the CV, not referenced.
Otherwise they can be changed after setting them.
> Make copy of client callback.

- Open62541.xs
- t/client-browse-async.t
- t/client-browse.t
- t/client-browsenext-async.t
- t/client-read-async.t
* The original idea for ExtensionObjects in perl was to have the content
in a separate hash. But XS_pack_UA_ExtensionObject() did not do this
until now and placed the content keys directly into th ExtensionObject
hash.
* This caused issues when trying to unpack previously packed
ExtensionObjects.
> Make pack/unpack of ExtensionObject consistent

- Open62541.xs
According to documentation, server node context may be NULL if node
is created by client.  Store undef context as NULL and handle NULL
properly in the gobal node lifecycle constructor.
> Handle NULL node context.

- lib/OPCUA/Open62541/Test/Server.pm
- t/server-client-variable.t
- t/server-variable.t
- t/test-server-runtimeaction.t
- t/unicode.t
* Until now the ValueRank was not explicitly set for variable nodes,
which meant that the value was 0 (indicating an array). This was wrong
and also will not work with newer versions of open62541.
* Fixed the ValueRank attribute in all addVariableNode calls.
> Fix ValueRank in Tests

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/client-config-context.t
Implement a wrapper for client context.  This can be used for client
callbacks later.
> Set client context in config.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/client-statecallback.t
Store Perl callback in client config.  Register open62541 stateCallback.
Remember client SV from client get config.  This is the least ugly
way to provide the Perl object for the state callback.  The API of
stateCallback depends on open62541 library version.
> Implement state callback.

- Open62541.xs
- t/server-node-lifecycle.t
Free node context if server add node has failed.  If call is
successful, the callback has freed it.  Set the output node only
after it has been added successfully.  Test node context leak and
out node.
> Fix memory leak in server add node.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/client-subscription.t
* This implements user-defined callbacks for subscribtion change
notifications and deletions. There are some differences in comparison
to already existing callback code.
* We have to create 2 callback data structures in one function. So the
subscription context is an array of 2 ClientCallbackData elements
(instead of just one).
* The existing callbacks always passed a request ID and the service
response to the perl callback. Subscription callbacks have different
arguments (subscription ID for deletion, subscription ID and
notification for change notification). Maybe this logic can be
combined/refactored later with the old code.
* I don't really see the possibility to trigger a change notification in
the open62541 server. So there is no test for that callback at the
moment.
> Subscriptions - Subscriptions_create callbacks

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/client-subscription.t
- t/server-config-default.t
* Most of the subscription limits from server_config.h can now be read
and written with get/set functions.
* "publishingIntervalLimits", "lifeTimeCountLimits" and
"keepAliveCountLimits" are skipped because the underlying range data
structures are missing some initialization functions in the open62541
library and the pack/unpack functions would need special handling.
* There is also now a test that looks for leaks if the
Subscriptions_create() function fails and this test also uncovered a
typo/bug in the existing cleanup code.
* I also adapted one of the subscription callback tests, to actually get
the context from the callback arguments and not use the context
variable from outside the callback.
> Subscriptions - Limits

- MANIFEST
- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/client-subscription.t
* Reorder callback defines according to order in client_subscriptions.h
* Print C callback debug message regardless of perl callback
* Reorder perl callback arguments to be the same as the C callback
* Renamed generic "sv" to a better name
* Added missing subscription test to MANIFEST
> Subscriptions - Cleanup

- Open62541.xs
Pass subscription and monitored item context as struct instead of array of pointers.
> Subscription struct

- Open62541.xs
- t/client-monitoreditems.t
The new monitored item create request will contain a copy of the
given node Id.  It will manage its memory.  So we have to duplicate
the node Id.
> Fix memory management of MonitoredItemCreateRequest_default()

- Open62541.xs
- t/client-monitoreditems.t
The open62541 library behaves inconsistently whether callbacks will
be called if registering the callback fails.  This make memory
managent hard, especially when multiple versions of the library
should be supported.
Register a pointer to the monitored item context and delete it if
the delete callback is called.  If the pointer is not NULL, the
callback data is still pending and must be freed.
> Detect call to monitored item delete callback.

- Open62541.xs
- t/client-monitoreditems.t
- typemap
The UA_Client_MonitoredItems_createDataChanges() has ugly callback
semantics.  It does not expect a void pointer where we could store
all our data structures, but an array of void pointers.  Create a
Perl PV object that contains the C arrays needed by the open62541
function.  This container is referenced by every callback context.
Each time a delete callback is executed, the reference counter is
decremented.  After all delete callbacks have been called, the C
memory is freed by the Perl destroy function.
Also monitored items without Perl callback need this data structure.
So the test has to iterate and free the memory as it its detected
by the leak tracer.
> Use MonitoredItemArrays to implement callback memory management.

- .github/workflows/main.yml
- t/server-config-default.t
* We build open62541 manually now, because we want to test multiple
versions simultaneously and 1.3 is not availably in the apt repo yet.
* Build and dependency installation are adjusted to what we need.
* We switch from ubuntu:20.04 to ubuntu:latest because this seems more
future proof (also 20.04 is equal to latest at the moment).
* We build open62541 in /tmp, because ExtUtils will otherwise complain,
if it finds multiple versions of the same library.
* Since we now build from the git repository, the buildNumber seems to
be the build date. The server-config-default.t was adjusted
accordingly.
> CI: manually build different open62541 versions

- .github/workflows/main.yml
* python3 is already installed in the image and we don't need python2.
> CI: remove python2 dependency

- Open62541.xs
open62541 version 1.3 removed typeIndex, use pointer arithmetic as
a workaround.  dataType2Index() compares the DataType pointer with
UA_TYPES.
> Replace UA_DataType typeIndex with pointer arithmetic.

- Makefile.PL
- Open62541.xs
UA_ServerConfig_setCustomHostname() has been deprecated in open62541
version 1.2 and removed in 1.3.  Use #ifdef to create the Perl
wrapper only if the function exists.
> Server Config set Custom Hostname function has been removed.

- Makefile.PL
- Open62541-packed.xsh
Changes in the standard require changes in the generated type
packers.  Add some manual #ifdefs for now.  Find a smart solution
before regenerating.
> OPC UA genrated types have changed.

- Open62541.xs
open62531 1.1 API changed timeout parameter of UA_Client_run_iterate()
from UA_UInt16 to UA_UInt32.  Adapt types in wrapper.
> Client iterate has 32 bit timeout.

- Open62541.xs
- t/client-config-context.t
- t/client-config.t
Client config may be destroyed multiple times as its memory life
time is coupled to the client lifetime.  The same object is contructed
multiple times in getConfig().  This resulted in double frees of
its members.  Move the client context and state callback destruction
from client config destroy to client destroy.  Test client config
destroy with context and callback refcount.  Make client config
context leak test a bit more paranoid.
> Move context and callback destruction to client destroy.

- lib/OPCUA/Open62541/Test/Server.pm
TCP layer in open62541 master has been refactored, so the log
messages changed.  Adapt test server to detect startup by TCP listen
socket.
> Adapt regex for server startup.

- Open62541.xs
- lib/OPCUA/Open62541.pm
The API for client async connect and disconnect has changed in
open62541 1.1.  Provide old and new implementation with ifdef.  Also
update client getState() documentation.  The tests for the new API
are more complicated due to new semantics of UA_Client_connectAsync()
and UA_Client_disconnectAsync().  Just provide the new functions
for now.  Using them correctly is the next step.
> Implement client async connect and disconnect with 1.1 API.

- lib/OPCUA/Open62541/Test/Client.pm
- t/client-connect-async.t
- t/client-disconnect-async.t
- t/client-statecallback.t
- t/test-server-singlestep.t
Until now the async tests were skipped in case the 1.1 API provides
new UA_Client_connectAsync() and UA_Client_disconnectAsync().  Make
client connect and disconnect async test work with both variants.
Test that connect after disconnect works with open62541 > 1.0.
Adapt test server singlestep to new API behavior.
> Test client async connect and disconnect with 1.1 API.

- Open62541.xs
- t/variant-scalar.t
* Since we checked for float overflows in XS_unpack_UA_Float, we were
not able to use infinity values. With the explicit check for infinity,
this is now possible.
* XS_unpack_UA_Float / Perl can take "Inf" and "Infinity".
XS_pack_UA_Float / Perl will return "Inf".
> Allow infinity in XS_unpack_UA_Float

- Open62541.xs
The debug output was confusing as it was not clear whether an
Open62541 client address was printed or an Opcua::Open62541 Perl
wrapper object.  The ua_ prefix makes the code consistent and clear.
> Call all UA_Client and UA_Server variables ua_client or ua_server.

- Makefile.PL
- Open62541.xs
- t/client-subscription.t
When open62541 1.1 introduced async monitored items, the callback
behavior of UA_Client_Subscriptions_create() changed.  It is no
longer necessary to free the resources at failure, the callback
will do it in most cases.  To prevent leaks, disconnect() must be
called in test.
> Client subscription create always calls callback.

- t/client-read-async.t
* With newer open62541 Versions, the behaviour for sourceTimestamp
values changed if reading was unsuccessful (open62541 4c658423).
* We now accept 1 and '' in the test to be compatible with old and new
behaviour.
> Fix t/client-read-async.t

- t/server-client-variable.t
* Depending on the open62541 Version, readValueAttribute_async returns
different data types (Variant/DataValue). To compensate for this in
the test, we just check if we have a DataValue hash and compare it's
variant component instead of the complete hash.
> Fix t/server-client-variable.t

- Open62541.xs
- t/server-node-lifecycle.t
If no node context is given, use PL_sv_undef as context.  Creating
context in constructor and passing it to destructor does not work
anymore.  This feature is not implemented cleanly in the library.
> Use global undef for node context.

- Open62541.xs
- t/client-connect-async-refcount.t
Client getConfig() sets client context to the client SV passed in.
When the client variable goes out of scope, the sv becomes invalid.
Refresh the context every time the client connects, disconnects or
iterates to have an valid SV in clientStateCallback().  This fixes
the test case triggered by client-connect-async-refcount.t.
> Fix clientStateCallback client context.

- .github/workflows/main.yml
* We will not fix the tests / make the module compatible for
open62541 1.2. So we can remove the 1.2 build from the CI.
* Update 1.3 to 1.3.2
> CI: update tags for builds

- .github/workflows/main.yml
The master runner does not terminate currently.
Disable for now until we have time to investigate.
> Disable open623541 master branch in github CI.

- Open62541-packed-type.xsh
- Open62541-packed.xsh
- Open62541.xs
- script/packed-type.pl
- script/patch-tools_generate_datatypes_py
- t/variant-array.t
- typemap
The non XS packers allow manipulation of half constructed object. Always link the objects before packing them.  Then a half created object will free its subobjects during croak.
> Call pack und unpack functions instead of XS wrappers.

- Open62541-packed.xsh
- Open62541.xs
- script/patch-tools_generate_datatypes_py
Make the input parameter of the pack conditions a const pointer to the UA object.  This allows to replace more XS_pack with pack as some XS funtions have constant parameters.
> Constify pack functions in parameter.

- Open62541.xs
Set minimal server config fills the build info with UA strings. Set build info in server config must clear the existing build info before copy new build info which allocates new UA strings.
> Before setting build info, clear existing strings.

- Open62541.xs
- t/variant-leak.t
If the call to variant getScalar() or getArray() croaks, the return SV must be released.  Add test that triggers leak in get and set variant.
> Fix leak in variant get scalar and get array.

- .github/workflows/main.yml
* Since node12 has been deprecated in github actions, the workflow should use checkout@v3 now.
> CI: switch to actions/checkout@v3

- Open62541.xs
- lib/OPCUA/Open62541.pm
- t/client-config-userpass.t
* If an empty string is given to UA_ClientConfig_setUsernamePassword(), the username/password data in the userIdentityToken of the client config is now cleared.
* Additionally the endpoint and userTokenPolicy data of the client config is cleared. This is necessary because open62541 will otherwise reuse the policy from a previous connection, which might be wrong (e. g. if the client switches from anonymous to user authentication).
* Because of this the client will make a new additional GetEndpoints request for the next connection (if the client already connected previously).
> UA_ClientConfig_setUsernamePassword: anonymous

- Changes
- lib/OPCUA/Open62541.pm
The removal of the open62541 1.0 and 1.1 API compatibility justifies a new major version.
> Bump version number to 2.00 and update change log.

- Open62541.xs
- lib/OPCUA/Open62541.pm
- lib/OPCUA/Open62541/Test/Client.pm
- t/client-config-encryption.t
* ClientConfig::setDefaultEncryption() will now handle given array references for the trust and revocation list.
* The data for the UA_ByteString arrays is held in a mortal SV. if something croaks, perl itself can free the data.
* Since the trust / revocation list SVs will live longer than the UA_ByteString arrays (UA_ClientConfig_setDefaultEncryption copies the data into the relevant pki plugin data structures), we can directly reference the passed SV string data in the UA_ByteString structures.
* At the moment we dont have any valid CRLs for the tests yet.
> ClientConfig - trust / revocation list

- MANIFEST
- t/CA.pm
- t/client-config-encryption.t
* New OPCUA::Open62541::Test::CA module in t/CA.pm that should only be used for tests. The module allows creation of certificates with IO::Socket::SSL::Utils and generating CRLs for these certificates with the openssl CLI.
* The module by default creates a directory "t/ca/" with some basic openssl stuff to create the CRLs.
> CRLs in Tests

- MANIFEST
- Open62541.xs
- lib/OPCUA/Open62541/Test/CA.pm
- lib/OPCUA/Open62541/Test/Server.pm
- t/client-config-encryption.t
- t/encryption.t
* Move CA.pm to lib/OPCUA/Open62541/Test/CA.pm
* Use IPC::Open3 instead of qx to catch STDERR without shell invocation
* Use File::Temp for temporary test directories. If a directory is given in new(), it will not be removed afterwards.
* Use more consistent paranthesis and quotation coding style
> More encryption

- .github/workflows/main.yml
* At the moment mbedtls returns a MBEDTLS_ERR_X509_INVALID_FORMAT error when trying to load CRLs. Disable mbedtls in the test matrix for now.
This reverts commit 8e84b5b4a7646e765772be31d5316aa05f0f7a05.
> Revert "CI: test with openssl + mbedtls"

- lib/OPCUA/Open62541/Test/CA.pm
- t/client-config-encryption.t
- t/encryption.t
* Rename create_cert_root() to create_cert_ca() since it can also be used to create intermediate CA certificates.
* Selfsigned non-root certificates don't need the CA flag. A new 'ca' parameter is now checked in create_cert() and create_cert_ca() is setting this parameter by default to true.
* Non CA certificates additionally now have the 'dataEncipherment' key usage (besides the 'digitalSignature' and 'keyEncipherment' defaults).
* t/client-config-encryption.t had to be fixed because the self signed certificate generates not a CRL anymore.
> OPCUA::Open62541::Test::CA - Better purpose

- Open62541.xs
- lib/OPCUA/Open62541/Test/Server.pm
- t/client-browse-async.t
- t/client-browse.t
- t/client-browsenext-async.t
- t/client-monitoreditems.t
- t/client-read-async.t
- t/server-browse.t
- t/server-node-lifecycle.t
- t/server-read.t
- t/server-references.t
- t/server-variable.t
To generate debugging output easier, add printable representation of NodeId into hash key NodeId_print.  This is always done in pack_UA_NodeId() so nodes received from open62541 can easily be printed.  Format is from OPC UA Part6 5.3.1.10 and looks like one of this:
i=13
ns=10;i=-1
ns=10;s=Hello:World
g=09087e75-8e5e-499b-954f-f2a9603db28a
ns=1;b=M/RbKBsRVkePCePcx24oRA==
> NodeId contains printable string as identifier.

- Open62541.xs
Lines are restricted to 80 characters, except where Perl XS requires single lines.  Wrap long XS functions with backslash.  Use brackets for multiline if.  Operator is at the end of a multiline.  No functional change.
> Warp long lines and fix style.

- Makefile.PL
- Open62541.xs
- t/server-config-setlogincheck.t
If open62541 library has implemented UA_AccessControl_setCallback(), it can be used to override the algorithm for username password login check.  As the OpenBSD libc function crypt_checkpass() is the easiest way to do it securely, provide loginCryptCheckpassCallback() if it exists.  This algorithm can be selected from Perl by passing the string "crypt_checkpass" to the server config method setAccessControl_loginCheck().
Note that UA_AccessControl_setCallback() has not been commited upstream and crypt_checkpass() exists only on OpenBSD.  Compiling the new feature is optional using #ifdef, corresponding tests are skipped.
The XS function UA_ServerConfig_AccessControl_CryptNewhash() is provided for convenience, to generate password hashes easily with Perl.
> Implement UA_ServerConfig_AccessControl_setLoginCheck.

- Makefile.PL
- Open62541.xs
- t/server-config-setlogincheck.t
Discussion with upstream open62541 revealed that a new function UA_AccessControl_defaultWithLoginCallback() is better than adding UA_AccessControl_setCallback() to set a single parameter.  Rework the Perl wrapper to reflect this change.  The server config method setAccessControl_defaultWithLoginCallback() works like setAccessControl_default(), but with an additional callback argument. Note that a pure Perl callback is not implemented, but only the string "crypt_checkpass" is supported.  This check is implemented using OpenBSD libC function.  A Perl callback would make it more complicated to use OpenBSD password hashes.
> Adapt to UA_AccessControl_defaultWithLoginCallback.

- t/server-config-accesscontrol.t
Remove default users and passwords from server config.  Test that login with username is rejected, but anonymous access still works.
> Test server with empty login list.

- .github/workflows/main.yml
- lib/OPCUA/Open62541/Test/CA.pm
Make the generated Application Instance Certificates more compliant to OPC UA Part 6 6.2.2 by
* adding serverAuth / clientAuth to extendedKeyUsage
* adding nonRepudiation to keyUsage
* adding 'OPCUA::Open62541' to the default subject CN
* adding 'host' argument for servers to be used as subjectAltName
> OPCUA::Open62541::Test::CA - Better certificates

- Open62541.xs
- t/server-config-accesscontrol.t
UA_AccessControl_default() requires a non-NULL userTokenPolicyUri if verifyX509 or usernamePasswordLoginSize is set. UA_ServerConfig_setDefaultWithSecurityPolicies() uses the last of the securityPolicies from the server config.  Try this as a fallback in UA_ServerConfig_setAccessControl_default() XS wrapper.
> Allow empty userTokenPolicyUri.

- Open62541.xs
Discussing the API of open62541 with upstream concluded that the session context should be added to the login callback.  Although not commited yet, make p5-opcua-open62541 compatible with future changes.  https://github.com/open62541/open62541/pull/5935
> Add session context to login callback.

- .github/workflows/main.yml
- Makefile.PL
- Open62541.xs
1.3.4 is used by genua OPC UA cyber-diode.
1.3.8 is used by OpenBSD port misc/open62541.
Track branches 1.3 and 1.4 to detect incompatibilites in advance.
> Update open62541 versions for github runner.

- Open62541.xs
- lib/OPCUA/Open62541.pm
The default timeout for the client is 5 seconds.
This makes this configurable via the client config.
> Implement timeout accessors for client config

- Open62541.xs
- lib/OPCUA/Open62541.pm
- typemap
* Service_browseNext() to browse continuation points
* Service_read() to specify the attributes with constants
Both functions were already implemented for their async variants.
> Implement some more missing client functions

- bin/opcua_dump.pl
This makes the OPC UA client timeout configurable while also introducing parsing parameters through a config file, setting default values and documentation.
> opcua_dump - configurable client timeout
