bluhm/p5-opcua-open62541

Open62541.xs
t/client-connect-async.t

This also makes the handling of callbacks to perl more abstract, because we will need to have different callbacks for different services.

Return request ID and response in async callbacks

---

Makefile.PL
Open62541.xs
Open62541TypeConversion.xs

TODO:
* Enumerated Types
* Opaque Types
* Array conversion Perl => C

Add auto-generated data conversion functions

---

Open62541.xs

* Add pack for UA_NodeId
* Add unpack/pack for QualifiedName and LocalizedText

Implement more pack/unpack functions

---

Open62541-packed.xsh

* Add conversion for enumerated types
* Add conversion for opaque types
* Add conversion for arrays

Add more auto-generated conversions

---

lib/OPCUA/Open62541.pm
lib/OPCUA/Open62541/NS0ID.pm
lib/OPCUA/Open62541/Test/Server.pm
t/critic.t
t/perlcriticrc
t/perltidyrc

Config file for perlcritic
Fix issues perlcritic found
Config file for perltidy
Perltidy is not yet enforced by perlcritic

Config for perlcritic

---

Open62541.xs
lib/OPCUA/Open62541.pm
lib/OPCUA/Open62541/Test/Client.pm
lib/OPCUA/Open62541/Test/Logger.pm
lib/OPCUA/Open62541/Test/Server.pm
t/client-connect-async.t
t/client-connect.t
t/logger-server.t
t/logger.t
t/perlcriticrc
t/test-client.t
t/test-server.t
typemap

The Logger can either be a standalone object or use the embedded
logger of a sever config.  In the latter case the life time is
entangled with the config.  It contains Perl callbacks to the log
and clear functions.  The log funtions are exported to Perl.

Implement Logger class.

---

Makefile.PL
t/client-browse-async.t

Use test client to start client.  Use Test::Deep to compare browse
output.  Split leak test from functional test.  Check that invalid
function parameter croak.

Test browse async reloaded.

---

Open62541.xs
t/client-browse-async.t
t/client-connect-async.t

If connect_async() or sendAsyncBrowseRequest() is not successful,
destroy the callback data and decrement the refcount of the content.

Do not leak if client callback is not called.

---

Open62541.xs
t/client-connect-async.t

If connect_async() is called more than once, only the first one
invokes the callback.  Then do not allocate the callback data to
avoid a memory leak.

Plug a memory leak in connect_async().

---

Open62541.xs
lib/OPCUA/Open62541.pm
t/server-client-variable.t

Add basic test similar to test for sendAsyncBrowseRequest.

Implement UA_Client_readValueAttribute_async()

---

Open62541.xs

To avoid complexity when freeing objects, embed the structures that
are the base for the Perl objects the same way as it is done in the
open62541 library.  The client or server structs are the only objects
that are malloced.  They contain the config which contains the
logger.  So the client or server must be freed last.  This is assured
by incrementing their Perl reference count each time a config or
logger is created.  When these are destroyed they decrement the
reference count and trigger client or server destruction.

Embed config and logger struct into client and server.

---

Open62541.xs
lib/OPCUA/Open62541.pm
typemap

New functions:
addVariableTypeNode, addObjectNode, addObjectTypeNode, addViewNode,
addReferenceTypeNode, addDataTypeNode
Still missing functions:
* UA_Server_addDataSourceVariableNode is a special case for creating
variable nodes
* UA_Server_addMethodNode needs some missing pack/unpack functions

Add more functions to add nodes

---

lib/OPCUA/Open62541/Test/Client.pm

* The URL can be set in new()
* The library will use the default port if no port was given
* start() will no longer overwrite the URL

Improve OPCUA::Open62541::Test::Client Usability

---

MANIFEST
Open62541.xs
lib/OPCUA/Open62541.pm
lib/OPCUA/Open62541/Test/Server.pm
t/server-browse.t
typemap

* Added browse() for the Server
* Added some general setup of an object node with a complex type in the
OPC UA test server for later reuse in other tests.

Add UA_Server_browse

---

lib/OPCUA/Open62541.pm

* The $nodecontext variable for various node adding functions was
documented inconsistently.

Fix documentation inconsistencies

---

MANIFEST
Open62541.xs
t/client-browsenext-async.t
typemap

* The highlevel client API 1.0 does not support async BrowseNext
requests. So we use the lower level sendAsyncRequest for this.

Implement sendAsyncBrowseNextRequest

---

Open62541.xs
t/server-node-lifecycle.t
t/server-variable.t

Set node context for constructor and destructor.

Node livecycle node context

---

Open62541.xs

Writing "data" to the C structure was missing.

Fix XS_unpack_UA_ExtensionObject

---

Open62541.xs
t/client-monitoreditems-multiple.t

Plug some memory leaks in MonitoredItems_createDataChanges()
and make it compatible with newer version of open62541 library.

Mon deletes

---

Open62541.xs

There are many add node funtions in the server that share common
code.  Move this code into functions to make refactoring easier.
If there are neither constructor nor destructor, it is not necessary
to set up a node context SV.  Increment the references counter in
the prolog to ensure that it exists, even if the destructor has
deleted it.  Then the prolog can decrement the references counter,
taking into account if the destructort exists, has alread deleted
it or something went wrong during node creation.  The callback logic
of open26541 is so absurd that it is pure luck to find the correct
condition to destroy the SV.

Use prolog and epilog for server add node functions.

---

t/client-connect-async.t

If 3-way handshake fails, the connection status is BadDisconnect.
Some other timing gives BadConnectionClosed.  On Linux it is always
Good.  To make t/client-connect-async.t reliable, expect any of
these status codes.

Fix race in client connect async test.

---

Open62541.xs
t/logger-client.t
t/logger-server.t
t/logger.t

In open62541 master the logger output has changed.  Add eventloop
log category.  Adapt logger, client and server tests.

Adapt expected log strings.

---

Open62541-packed-type.xsh
Open62541.xs
script/packed-type.pl

Table pack gets a pointer to const data, unpack swaps parameter to
out and in.

Table pack functions look like pack functions.

---

t/client-config-encryption.t
t/encryption.t

* With the new module to generate CRLs, we can now test various encryption test cases with different server certificates / validation by the client.

Tests: validating server certificate

---

Open62541.xs

Move conversion from Perl string array to UA_ByteString list and size into sepearate function to avoid code duplication.

Implement unpack_UA_ByteString_List().

---

Open62541.xs
t/server-config-accesscontrol.t
typemap

Implement setAccessControl_default() as an method of server config. Call UA_AccessControl_default() with this server config.  The username password login structure is passed as an array of hashes. CertificateVerification is a special object passed as optional parameter.

Implement UA_ServerConfig_setAccessControl_default.

---

lib/OPCUA/Open62541/Test/CA.pm

This makes the Application URI in SubjectAltname configurable.

 OPCUA::Open62541::Test::CA - application_uri

---

MANIFEST
Open62541.xs
t/server-config-endpoints.t

Adds accessors to retrieve and change the endpoints array in the server config. This allows the user to only configure encrypted endpoints.

Add ServerConfig endpoints accessor

---

.github/workflows/main.yml
lib/OPCUA/Open62541/Test/Client.pm
lib/OPCUA/Open62541/Test/Server.pm
t/client-config-applicationuri.t
t/encryption.t
t/server-config-cutomhostname.t
t/server-config-endpoints.t
t/server-config-setlogincheck.t

Tests must pass with open62541 version 1.3.15.

Open62541 1.3.15

---

bin/opcua_dump.pl
lib/OPCUA/Open62541.pm
lib/OPCUA/Open62541/Client.pm
t/client-highlevel.t

Follow up changes to the newly imported opcua_dump tool.

opcua_dump cleanup
